# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Jun  6 17:35:02 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(595, 379)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.commandLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.commandLineEdit.setObjectName(_fromUtf8("commandLineEdit"))
        self.horizontalLayout.addWidget(self.commandLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ipLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ipLineEdit.setObjectName(_fromUtf8("ipLineEdit"))
        self.horizontalLayout_2.addWidget(self.ipLineEdit)
        self.scanPushButton = QtGui.QPushButton(self.centralwidget)
        self.scanPushButton.setObjectName(_fromUtf8("scanPushButton"))
        self.horizontalLayout_2.addWidget(self.scanPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.scanTab = QtGui.QWidget()
        self.scanTab.setObjectName(_fromUtf8("scanTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scanTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.scanTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.tcpComboBox = QtGui.QComboBox(self.scanTab)
        self.tcpComboBox.setObjectName(_fromUtf8("tcpComboBox"))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tcpComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.scanTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.nonTcpComboBox = QtGui.QComboBox(self.scanTab)
        self.nonTcpComboBox.setObjectName(_fromUtf8("nonTcpComboBox"))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.nonTcpComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.scanTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.speedSpinBox = QtGui.QSpinBox(self.scanTab)
        self.speedSpinBox.setMaximum(5)
        self.speedSpinBox.setObjectName(_fromUtf8("speedSpinBox"))
        self.horizontalLayout_7.addWidget(self.speedSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.OSCheckBox = QtGui.QCheckBox(self.scanTab)
        self.OSCheckBox.setObjectName(_fromUtf8("OSCheckBox"))
        self.verticalLayout_3.addWidget(self.OSCheckBox)
        self.shortCheckBox = QtGui.QCheckBox(self.scanTab)
        self.shortCheckBox.setObjectName(_fromUtf8("shortCheckBox"))
        self.verticalLayout_3.addWidget(self.shortCheckBox)
        self.versionsCheckBox = QtGui.QCheckBox(self.scanTab)
        self.versionsCheckBox.setObjectName(_fromUtf8("versionsCheckBox"))
        self.verticalLayout_3.addWidget(self.versionsCheckBox)
        self.tabWidget.addTab(self.scanTab, _fromUtf8(""))
        self.pingTab = QtGui.QWidget()
        self.pingTab.setObjectName(_fromUtf8("pingTab"))
        self.gridLayout = QtGui.QGridLayout(self.pingTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.noPingCheckBox = QtGui.QCheckBox(self.pingTab)
        self.noPingCheckBox.setObjectName(_fromUtf8("noPingCheckBox"))
        self.gridLayout.addWidget(self.noPingCheckBox, 0, 0, 1, 1)
        self.icmpCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpCheckBox.setObjectName(_fromUtf8("icmpCheckBox"))
        self.gridLayout.addWidget(self.icmpCheckBox, 1, 0, 1, 1)
        self.icmpTimeLableCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpTimeLableCheckBox.setObjectName(_fromUtf8("icmpTimeLableCheckBox"))
        self.gridLayout.addWidget(self.icmpTimeLableCheckBox, 2, 0, 1, 1)
        self.icmpNetmaskCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpNetmaskCheckBox.setObjectName(_fromUtf8("icmpNetmaskCheckBox"))
        self.gridLayout.addWidget(self.icmpNetmaskCheckBox, 3, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.ackCheckBox = QtGui.QCheckBox(self.pingTab)
        self.ackCheckBox.setObjectName(_fromUtf8("ackCheckBox"))
        self.horizontalLayout_18.addWidget(self.ackCheckBox)
        self.ackLineEdit = QtGui.QLineEdit(self.pingTab)
        self.ackLineEdit.setObjectName(_fromUtf8("ackLineEdit"))
        self.horizontalLayout_18.addWidget(self.ackLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.synCheckBox = QtGui.QCheckBox(self.pingTab)
        self.synCheckBox.setObjectName(_fromUtf8("synCheckBox"))
        self.horizontalLayout_19.addWidget(self.synCheckBox)
        self.synLineEdit = QtGui.QLineEdit(self.pingTab)
        self.synLineEdit.setObjectName(_fromUtf8("synLineEdit"))
        self.horizontalLayout_19.addWidget(self.synLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_19, 5, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.udpCheckBox = QtGui.QCheckBox(self.pingTab)
        self.udpCheckBox.setObjectName(_fromUtf8("udpCheckBox"))
        self.horizontalLayout_20.addWidget(self.udpCheckBox)
        self.udpLineEdit = QtGui.QLineEdit(self.pingTab)
        self.udpLineEdit.setObjectName(_fromUtf8("udpLineEdit"))
        self.horizontalLayout_20.addWidget(self.udpLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_20, 6, 0, 1, 1)
        self.tabWidget.addTab(self.pingTab, _fromUtf8(""))
        self.otherTab = QtGui.QWidget()
        self.otherTab.setObjectName(_fromUtf8("otherTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.otherTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verboseCheckBox = QtGui.QCheckBox(self.otherTab)
        self.verboseCheckBox.setObjectName(_fromUtf8("verboseCheckBox"))
        self.verticalLayout_4.addWidget(self.verboseCheckBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.portsCheckBox = QtGui.QCheckBox(self.otherTab)
        self.portsCheckBox.setObjectName(_fromUtf8("portsCheckBox"))
        self.horizontalLayout_10.addWidget(self.portsCheckBox)
        self.portsLineEdit = QtGui.QLineEdit(self.otherTab)
        self.portsLineEdit.setObjectName(_fromUtf8("portsLineEdit"))
        self.horizontalLayout_10.addWidget(self.portsLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.otherTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.outputTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outputTextEdit = QtGui.QTextEdit(self.outputTab)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.horizontalLayout_4.addWidget(self.outputTextEdit)
        self.tabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.portsTab = QtGui.QWidget()
        self.portsTab.setObjectName(_fromUtf8("portsTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.portsTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.outputTableWidget = QtGui.QTableWidget(self.portsTab)
        self.outputTableWidget.setObjectName(_fromUtf8("outputTableWidget"))
        self.outputTableWidget.setColumnCount(5)
        self.outputTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_3.addWidget(self.outputTableWidget)
        self.tabWidget.addTab(self.portsTab, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionQt = QtGui.QAction(mainWindow)
        self.actionQt.setObjectName(_fromUtf8("actionQt"))
        self.helpAction = QtGui.QAction(mainWindow)
        self.helpAction.setObjectName(_fromUtf8("helpAction"))
        self.aboutAuthorAction = QtGui.QAction(mainWindow)
        self.aboutAuthorAction.setObjectName(_fromUtf8("aboutAuthorAction"))
        self.nmapPathAction = QtGui.QAction(mainWindow)
        self.nmapPathAction.setObjectName(_fromUtf8("nmapPathAction"))
        self.menu.addAction(self.nmapPathAction)
        self.menu.addAction(self.aboutAuthorAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Mapn", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Команда nmap           ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Цель сканирования", None, QtGui.QApplication.UnicodeUTF8))
        self.scanPushButton.setText(QtGui.QApplication.translate("mainWindow", "Сканировать", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(0, QtGui.QApplication.translate("mainWindow", "Нет", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(1, QtGui.QApplication.translate("mainWindow", "SYN (-sS)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(2, QtGui.QApplication.translate("mainWindow", "При помощи соединения (-sT)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(3, QtGui.QApplication.translate("mainWindow", "FIN (-sF)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(4, QtGui.QApplication.translate("mainWindow", "ACK (-sA)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(5, QtGui.QApplication.translate("mainWindow", "Window (-sW)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(6, QtGui.QApplication.translate("mainWindow", "Мэймона (-sM)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(7, QtGui.QApplication.translate("mainWindow", "Null (-sN)", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpComboBox.setItemText(8, QtGui.QApplication.translate("mainWindow", "Xmass Tree (-sX)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "Не TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.nonTcpComboBox.setItemText(0, QtGui.QApplication.translate("mainWindow", "Нет", None, QtGui.QApplication.UnicodeUTF8))
        self.nonTcpComboBox.setItemText(1, QtGui.QApplication.translate("mainWindow", "UDP (-sU)", None, QtGui.QApplication.UnicodeUTF8))
        self.nonTcpComboBox.setItemText(2, QtGui.QApplication.translate("mainWindow", "IP протокол (-sO)", None, QtGui.QApplication.UnicodeUTF8))
        self.nonTcpComboBox.setItemText(3, QtGui.QApplication.translate("mainWindow", "Ping (-sP)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "Скорость исследования (-T)", None, QtGui.QApplication.UnicodeUTF8))
        self.OSCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Определить ОС (-O)", None, QtGui.QApplication.UnicodeUTF8))
        self.shortCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Корокий список портов (-F)", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Определить версии служб (-sV)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QtGui.QApplication.translate("mainWindow", "Сканирование", None, QtGui.QApplication.UnicodeUTF8))
        self.noPingCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Считать, что все узлы активны (-PN)", None, QtGui.QApplication.UnicodeUTF8))
        self.icmpCheckBox.setText(QtGui.QApplication.translate("mainWindow", "ICMP (-PE)", None, QtGui.QApplication.UnicodeUTF8))
        self.icmpTimeLableCheckBox.setText(QtGui.QApplication.translate("mainWindow", "ICMP запросы временной метки (-PP)", None, QtGui.QApplication.UnicodeUTF8))
        self.icmpNetmaskCheckBox.setText(QtGui.QApplication.translate("mainWindow", "ICMP запросы маски сети (-PM)", None, QtGui.QApplication.UnicodeUTF8))
        self.ackCheckBox.setText(QtGui.QApplication.translate("mainWindow", "ACK ping (-PA)      ", None, QtGui.QApplication.UnicodeUTF8))
        self.synCheckBox.setText(QtGui.QApplication.translate("mainWindow", "SYN ping (-PS)       ", None, QtGui.QApplication.UnicodeUTF8))
        self.udpCheckBox.setText(QtGui.QApplication.translate("mainWindow", "UDP probes (-PU)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pingTab), QtGui.QApplication.translate("mainWindow", "Обнаружение", None, QtGui.QApplication.UnicodeUTF8))
        self.verboseCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Выводить подробную инф (-v)", None, QtGui.QApplication.UnicodeUTF8))
        self.portsCheckBox.setText(QtGui.QApplication.translate("mainWindow", "Сканировать порты (-p)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.otherTab), QtGui.QApplication.translate("mainWindow", "Другое", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), QtGui.QApplication.translate("mainWindow", "Вывод Nmap", None, QtGui.QApplication.UnicodeUTF8))
        item = self.outputTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("mainWindow", "IP адрес", None, QtGui.QApplication.UnicodeUTF8))
        item = self.outputTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("mainWindow", "Порт", None, QtGui.QApplication.UnicodeUTF8))
        item = self.outputTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("mainWindow", "Протокол", None, QtGui.QApplication.UnicodeUTF8))
        item = self.outputTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("mainWindow", "Состояние", None, QtGui.QApplication.UnicodeUTF8))
        item = self.outputTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("mainWindow", "Сервис", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portsTab), QtGui.QApplication.translate("mainWindow", "Порты", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("mainWindow", "Меню", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQt.setText(QtGui.QApplication.translate("mainWindow", "Информация о Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setText(QtGui.QApplication.translate("mainWindow", "Справка", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAuthorAction.setText(QtGui.QApplication.translate("mainWindow", "Об авторе", None, QtGui.QApplication.UnicodeUTF8))
        self.nmapPathAction.setText(QtGui.QApplication.translate("mainWindow", "Добавить путь к Nmap", None, QtGui.QApplication.UnicodeUTF8))

