# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mapnWindow.ui'
#
# Created: Fri May 08 18:16:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapnWindow(object):
    def setupUi(self, mapnWindow):
        mapnWindow.setObjectName(_fromUtf8("mapnWindow"))
        mapnWindow.resize(595, 379)
        self.centralwidget = QtGui.QWidget(mapnWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.commandLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.commandLineEdit.setObjectName(_fromUtf8("commandLineEdit"))
        self.horizontalLayout.addWidget(self.commandLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ipLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ipLineEdit.setObjectName(_fromUtf8("ipLineEdit"))
        self.horizontalLayout_2.addWidget(self.ipLineEdit)
        self.scanPushButton = QtGui.QPushButton(self.centralwidget)
        self.scanPushButton.setObjectName(_fromUtf8("scanPushButton"))
        self.horizontalLayout_2.addWidget(self.scanPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.scanTab = QtGui.QWidget()
        self.scanTab.setObjectName(_fromUtf8("scanTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scanTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.scanTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.tcpComboBox = QtGui.QComboBox(self.scanTab)
        self.tcpComboBox.setObjectName(_fromUtf8("tcpComboBox"))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.tcpComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tcpComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.scanTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.nonTcpComboBox = QtGui.QComboBox(self.scanTab)
        self.nonTcpComboBox.setObjectName(_fromUtf8("nonTcpComboBox"))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.nonTcpComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.nonTcpComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.scanTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.speedSpinBox = QtGui.QSpinBox(self.scanTab)
        self.speedSpinBox.setMaximum(5)
        self.speedSpinBox.setObjectName(_fromUtf8("speedSpinBox"))
        self.horizontalLayout_7.addWidget(self.speedSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.OSCheckBox = QtGui.QCheckBox(self.scanTab)
        self.OSCheckBox.setObjectName(_fromUtf8("OSCheckBox"))
        self.verticalLayout_3.addWidget(self.OSCheckBox)
        self.shortCheckBox = QtGui.QCheckBox(self.scanTab)
        self.shortCheckBox.setObjectName(_fromUtf8("shortCheckBox"))
        self.verticalLayout_3.addWidget(self.shortCheckBox)
        self.versionsCheckBox = QtGui.QCheckBox(self.scanTab)
        self.versionsCheckBox.setObjectName(_fromUtf8("versionsCheckBox"))
        self.verticalLayout_3.addWidget(self.versionsCheckBox)
        self.tabWidget.addTab(self.scanTab, _fromUtf8(""))
        self.pingTab = QtGui.QWidget()
        self.pingTab.setObjectName(_fromUtf8("pingTab"))
        self.gridLayout = QtGui.QGridLayout(self.pingTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.noPingCheckBox = QtGui.QCheckBox(self.pingTab)
        self.noPingCheckBox.setObjectName(_fromUtf8("noPingCheckBox"))
        self.gridLayout.addWidget(self.noPingCheckBox, 0, 0, 1, 1)
        self.icmpCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpCheckBox.setObjectName(_fromUtf8("icmpCheckBox"))
        self.gridLayout.addWidget(self.icmpCheckBox, 1, 0, 1, 1)
        self.icmpTimeLableCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpTimeLableCheckBox.setObjectName(_fromUtf8("icmpTimeLableCheckBox"))
        self.gridLayout.addWidget(self.icmpTimeLableCheckBox, 2, 0, 1, 1)
        self.icmpNetmaskCheckBox = QtGui.QCheckBox(self.pingTab)
        self.icmpNetmaskCheckBox.setObjectName(_fromUtf8("icmpNetmaskCheckBox"))
        self.gridLayout.addWidget(self.icmpNetmaskCheckBox, 3, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.ackCheckBox = QtGui.QCheckBox(self.pingTab)
        self.ackCheckBox.setObjectName(_fromUtf8("ackCheckBox"))
        self.horizontalLayout_18.addWidget(self.ackCheckBox)
        self.ackLineEdit = QtGui.QLineEdit(self.pingTab)
        self.ackLineEdit.setObjectName(_fromUtf8("ackLineEdit"))
        self.horizontalLayout_18.addWidget(self.ackLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.synCheckBox = QtGui.QCheckBox(self.pingTab)
        self.synCheckBox.setObjectName(_fromUtf8("synCheckBox"))
        self.horizontalLayout_19.addWidget(self.synCheckBox)
        self.synLineEdit = QtGui.QLineEdit(self.pingTab)
        self.synLineEdit.setObjectName(_fromUtf8("synLineEdit"))
        self.horizontalLayout_19.addWidget(self.synLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_19, 5, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.udpCheckBox = QtGui.QCheckBox(self.pingTab)
        self.udpCheckBox.setObjectName(_fromUtf8("udpCheckBox"))
        self.horizontalLayout_20.addWidget(self.udpCheckBox)
        self.udpLineEdit = QtGui.QLineEdit(self.pingTab)
        self.udpLineEdit.setObjectName(_fromUtf8("udpLineEdit"))
        self.horizontalLayout_20.addWidget(self.udpLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_20, 6, 0, 1, 1)
        self.tabWidget.addTab(self.pingTab, _fromUtf8(""))
        self.otherTab = QtGui.QWidget()
        self.otherTab.setObjectName(_fromUtf8("otherTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.otherTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verboseCheckBox = QtGui.QCheckBox(self.otherTab)
        self.verboseCheckBox.setObjectName(_fromUtf8("verboseCheckBox"))
        self.verticalLayout_4.addWidget(self.verboseCheckBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.portsCheckBox = QtGui.QCheckBox(self.otherTab)
        self.portsCheckBox.setObjectName(_fromUtf8("portsCheckBox"))
        self.horizontalLayout_10.addWidget(self.portsCheckBox)
        self.portsLineEdit = QtGui.QLineEdit(self.otherTab)
        self.portsLineEdit.setObjectName(_fromUtf8("portsLineEdit"))
        self.horizontalLayout_10.addWidget(self.portsLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.otherTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.outputTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outputTextEdit = QtGui.QTextEdit(self.outputTab)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.horizontalLayout_4.addWidget(self.outputTextEdit)
        self.tabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.portsTab = QtGui.QWidget()
        self.portsTab.setObjectName(_fromUtf8("portsTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.portsTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.outputTableWidget = QtGui.QTableWidget(self.portsTab)
        self.outputTableWidget.setObjectName(_fromUtf8("outputTableWidget"))
        self.outputTableWidget.setColumnCount(5)
        self.outputTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_3.addWidget(self.outputTableWidget)
        self.tabWidget.addTab(self.portsTab, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        mapnWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mapnWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        mapnWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mapnWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mapnWindow.setStatusBar(self.statusbar)
        self.actionQt = QtGui.QAction(mapnWindow)
        self.actionQt.setObjectName(_fromUtf8("actionQt"))
        self.helpAction = QtGui.QAction(mapnWindow)
        self.helpAction.setObjectName(_fromUtf8("helpAction"))
        self.aboutAuthorAction = QtGui.QAction(mapnWindow)
        self.aboutAuthorAction.setObjectName(_fromUtf8("aboutAuthorAction"))
        self.nmapPathAction = QtGui.QAction(mapnWindow)
        self.nmapPathAction.setObjectName(_fromUtf8("nmapPathAction"))
        self.menu.addAction(self.nmapPathAction)
        self.menu.addAction(self.aboutAuthorAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mapnWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapnWindow)

    def retranslateUi(self, mapnWindow):
        mapnWindow.setWindowTitle(_translate("mapnWindow", "Mapn", None))
        self.label.setText(_translate("mapnWindow", "Команда nmap           ", None))
        self.label_2.setText(_translate("mapnWindow", "Цель сканирования", None))
        self.scanPushButton.setText(_translate("mapnWindow", "Сканировать", None))
        self.label_4.setText(_translate("mapnWindow", "TCP", None))
        self.tcpComboBox.setItemText(0, _translate("mapnWindow", "Нет", None))
        self.tcpComboBox.setItemText(1, _translate("mapnWindow", "SYN (-sS)", None))
        self.tcpComboBox.setItemText(2, _translate("mapnWindow", "При помощи соединения (-sT)", None))
        self.tcpComboBox.setItemText(3, _translate("mapnWindow", "FIN (-sF)", None))
        self.tcpComboBox.setItemText(4, _translate("mapnWindow", "ACK (-sA)", None))
        self.tcpComboBox.setItemText(5, _translate("mapnWindow", "Window (-sW)", None))
        self.tcpComboBox.setItemText(6, _translate("mapnWindow", "Мэймона (-sM)", None))
        self.tcpComboBox.setItemText(7, _translate("mapnWindow", "Null (-sN)", None))
        self.tcpComboBox.setItemText(8, _translate("mapnWindow", "Xmass Tree (-sX)", None))
        self.label_6.setText(_translate("mapnWindow", "Не TCP", None))
        self.nonTcpComboBox.setItemText(0, _translate("mapnWindow", "Нет", None))
        self.nonTcpComboBox.setItemText(1, _translate("mapnWindow", "UDP (-sU)", None))
        self.nonTcpComboBox.setItemText(2, _translate("mapnWindow", "IP протокол (-sO)", None))
        self.nonTcpComboBox.setItemText(3, _translate("mapnWindow", "Ping (-sP)", None))
        self.label_5.setText(_translate("mapnWindow", "Скорость исследования (-T)", None))
        self.OSCheckBox.setText(_translate("mapnWindow", "Определить ОС (-O)", None))
        self.shortCheckBox.setText(_translate("mapnWindow", "Корокий список портов (-F)", None))
        self.versionsCheckBox.setText(_translate("mapnWindow", "Определить версии служб (-sV)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), _translate("mapnWindow", "Сканирование", None))
        self.noPingCheckBox.setText(_translate("mapnWindow", "Считать, что все узлы активны (-PN)", None))
        self.icmpCheckBox.setText(_translate("mapnWindow", "ICMP (-PE)", None))
        self.icmpTimeLableCheckBox.setText(_translate("mapnWindow", "ICMP запросы временной метки (-PP)", None))
        self.icmpNetmaskCheckBox.setText(_translate("mapnWindow", "ICMP запросы маски сети (-PM)", None))
        self.ackCheckBox.setText(_translate("mapnWindow", "ACK ping (-PA)      ", None))
        self.synCheckBox.setText(_translate("mapnWindow", "SYN ping (-PS)       ", None))
        self.udpCheckBox.setText(_translate("mapnWindow", "UDP probes (-PU)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pingTab), _translate("mapnWindow", "Обнаружение", None))
        self.verboseCheckBox.setText(_translate("mapnWindow", "Выводить подробную инф (-v)", None))
        self.portsCheckBox.setText(_translate("mapnWindow", "Сканировать порты (-p)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.otherTab), _translate("mapnWindow", "Другое", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), _translate("mapnWindow", "Вывод Nmap", None))
        item = self.outputTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mapnWindow", "IP адрес", None))
        item = self.outputTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mapnWindow", "Порт", None))
        item = self.outputTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mapnWindow", "Протокол", None))
        item = self.outputTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mapnWindow", "Состояние", None))
        item = self.outputTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mapnWindow", "Сервис", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portsTab), _translate("mapnWindow", "Порты", None))
        self.menu.setTitle(_translate("mapnWindow", "Меню", None))
        self.actionQt.setText(_translate("mapnWindow", "Информация о Qt", None))
        self.helpAction.setText(_translate("mapnWindow", "Справка", None))
        self.aboutAuthorAction.setText(_translate("mapnWindow", "Об авторе", None))
        self.nmapPathAction.setText(_translate("mapnWindow", "Добавить путь к Nmap", None))

